# Do not forget to update other docker-compose files, especially in project-configuration repository.
version: '3.8'
services:
  backend:
    image: 913797522953.dkr.ecr.eu-west-1.amazonaws.com/stg-heart-backend
    build:
      context: backend
      dockerfile: HotPink.API/Dockerfile
    container_name: be
    restart: always
    expose:
      - 80
    ports:
      - "8080:80"
    depends_on:
      - video-processing
    logging:
      options:
        max-size: "20m"

  video-processing:
    image: 913797522953.dkr.ecr.eu-west-1.amazonaws.com/stg-heart-video-processing
    build:
      context: video_processing
      dockerfile: Dockerfile
    container_name: video-processing
    restart: always
    logging:
      options:
        max-size: "10m"

  frontend:
    image: 913797522953.dkr.ecr.eu-west-1.amazonaws.com/stg-heart-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: fe
    restart: always
    expose:
      - 80
    ports:
      - "8081:80"
    depends_on:
      - backend
